version: '3.6'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - ./docker/app.env
        image: pi-backend-api
        container_name: pi-backend
        volumes:
            - ./:/var/www/
        depends_on:
            - database
        ports:
            - 5173:5173
    database:
        image: postgres:latest
        ports:
            - 5434:5432
        container_name: pi-backend-database
        env_file:
            - ./docker/app.env
    webserver:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        image: pi-backend-server
        container_name: pi-backend-server
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
